---------------------------------------------------
-- Sheet: AND_Poort
-- RefDes: PLD1
-- Part Number: 
-- Generated By: Multisim
--
-- Author: 20002890
-- Date: Wednesday, February 06 11:20:45, 2019
---------------------------------------------------

---------------------------------------------------
-- Use: This file contains definitions of components
-- Use with the exported top-level file
---------------------------------------------------
library ieee;
use ieee.std_logic_1164.ALL;
use ieee.numeric_std.ALL;

package Voorbeeld1_and_gate_pkg is

	component AND2_NI
		port (
    B : in STD_LOGIC := 'X';
    A : in STD_LOGIC := 'X';
    Y : out STD_LOGIC := 'U'
  );
	end component;

	component AUTO_IBUF
		port(
		I : in std_logic;
		O : out std_logic
	);
	end component;

	component AUTO_OBUF
		port(
		I : in std_logic;
		O : out std_logic
	);
	end component;

end Voorbeeld1_and_gate_pkg;
package body Voorbeeld1_and_gate_pkg is
end Voorbeeld1_and_gate_pkg;


library work;
use work.Voorbeeld1_and_gate_pkg.ALL;
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;

entity AND2_NI is
  port (
    B : in STD_LOGIC := 'X';
    A : in STD_LOGIC := 'X';
    Y : out STD_LOGIC := 'U'
  );
end AND2_NI;

architecture BEHAVIORAL of AND2_NI is  

begin
  Y <= A and B;
end BEHAVIORAL;

library work;
use work.Voorbeeld1_and_gate_pkg.ALL;
library IEEE;
use IEEE.STD_LOGIC_1164.all;

entity AUTO_IBUF is
	port(
		I : in std_logic;
		O : out std_logic
	);end AUTO_IBUF;

architecture AUTO_IBUF_ARCH of AUTO_IBUF is

begin
 O <= I;
end AUTO_IBUF_ARCH;


library work;
use work.Voorbeeld1_and_gate_pkg.ALL;
library IEEE;
use IEEE.STD_LOGIC_1164.all;

entity AUTO_OBUF is
	port(
		I : in std_logic;
		O : out std_logic
	);end AUTO_OBUF;

architecture AUTO_OBUF_ARCH of AUTO_OBUF is

begin
 O <= I;
end AUTO_OBUF_ARCH;

