---------------------------------------------------
-- Sheet: AND_Poort
-- RefDes: PLD1
-- Part Number: 
-- Generated By: Multisim
--
-- Author: 20002890
-- Date: Wednesday, February 06 11:20:45, 2019
---------------------------------------------------

---------------------------------------------------
-- Use: This file defines the top-level of the design
-- Use with the exported package file
---------------------------------------------------
library ieee;
use ieee.std_logic_1164.ALL;
use ieee.numeric_std.ALL;

library work;
use work.Voorbeeld1_and_gate_pkg.ALL;


entity AND_Poort is
	port (

		INGANG1 : in std_logic;
		INGANG2 : in std_logic;
		UITGANG1 : out std_logic
	);
end AND_Poort;


architecture behavioral of AND_Poort is


	component AND2_NI
		port (
    B : in STD_LOGIC := 'X';
    A : in STD_LOGIC := 'X';
    Y : out STD_LOGIC := 'U'
  );
	end component;

	component AUTO_IBUF
		port(
		I : in std_logic;
		O : out std_logic
	);
	end component;

	component AUTO_OBUF
		port(
		I : in std_logic;
		O : out std_logic
	);
	end component;
	signal \1\ : std_logic;
	signal \3\ : std_logic;
	signal \2\ : std_logic;
begin
	INGANG1_AUTOBUF : AUTO_IBUF
		port map( I => INGANG1, O => \1\ );
	INGANG2_AUTOBUF : AUTO_IBUF
		port map( I => INGANG2, O => \2\ );
	UITGANG1_AUTOBUF : AUTO_OBUF
		port map( I => \3\, O => UITGANG1 );
	U1 : AND2_NI
		port map( A => \1\, B => \2\, Y => \3\ );
end behavioral;
