set_property SRC_FILE_INFO {cfile:C:/Users/20002890/11_VHDL_1819/11_VHDL_1819.srcs/constrs_1/new/and_gate.xdc rfile:../../../11_VHDL_1819.srcs/constrs_1/new/and_gate.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E13 [get_ports led]
set_property src_info {type:XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L15 [get_ports sw1]
set_property src_info {type:XDC file:1 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M15 [get_ports sw2]
