set_property IOSTANDARD LVCMOS33 [get_ports LED0]
set_property IOSTANDARD LVCMOS33 [get_ports SW0]
set_property IOSTANDARD LVCMOS33 [get_ports SW1]
set_property PACKAGE_PIN R14 [get_ports LED0]
set_property PACKAGE_PIN M20 [get_ports SW0]
set_property PACKAGE_PIN M19 [get_ports SW1]
