set_property SRC_FILE_INFO {cfile:C:/Users/20002890/minized_vhdl_no_clk/minized_vhdl_no_clk.srcs/constrs_1/new/vhdlnoclk.xdc rfile:../../../minized_vhdl_no_clk.srcs/constrs_1/new/vhdlnoclk.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E12 [get_ports r_led]
set_property src_info {type:XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E13 [get_ports g_led]
