set_property IOSTANDARD LVCMOS33 [get_ports led]
set_property IOSTANDARD LVCMOS33 [get_ports sw1]
set_property IOSTANDARD LVCMOS33 [get_ports sw2]
set_property PACKAGE_PIN E13 [get_ports led]
set_property PACKAGE_PIN L15 [get_ports sw1]
set_property PACKAGE_PIN M15 [get_ports sw2]
